[tool.poetry]
name = "advanced-python-project"
version = "0.1.0"
description = "Deep dive into Python"
authors = ["mpazaryna <mpazbot@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.2"
panda = "^0.3.1"
openai = "^1.36.0"
langchain = "^0.2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
